### ISSUE TITLE
Transfer repo to Techtonica organization

### ISSUE THREAD

**Issue by MichelleGlauser** [Techtonica/techtonica.org#124]
Make sure to reset the git remotes on the server and locally.

**Comment by hnarasaki** [comment]
Would this look like Techtonica/website ? Or how would you like it to look?

**Comment by hnarasaki** [comment]
Hi @MichelleGlauser, Due to security settings, you may need to move this one yourself (https://help.github.com/en/enterprise/2.15/user/articles/transferring-a-repository) unless you would like to temporarily grant rights to other users on MichelleGlauser/techtonica to move it to Techtonica/website. But it would probably be more secure if you move it.

**Comment by MichelleGlauser** [comment]
Complete! Remember to change your remotes using `git remote set-url origin https://github.com/Techtonica/techtonica.org.git`.
